### ISSUE TITLE
[Error with Typescript] - Could not find the declaration file for the lib modules

### ISSUE THREAD

**Issue by Madeuss** [Abhinandan-Kushwaha/react-gifted-charts#11]
Heey! 👋 
I'm getting this type error using the library with typescript: 
 
![image](https://github.com/user-attachments/assets/5290c346-8c49-4098-b417-34533409c0ba)

I've tried install the `@types/react-gifted-charts` with both (yarn and npm) but was not successful -  the types was not found

![image](https://github.com/user-attachments/assets/22f146fa-7bf9-41e8-a6c1-cfeb8671ad02)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Madeuss 👋
Thanks for reporting this issue. It has been fixed from versions `0.0.6` onwards. 🎉

Please use the latest version of the library.
