### ISSUE TITLE
renderTooltip not working

### ISSUE THREAD

**Issue by kaumac** [Abhinandan-Kushwaha/react-gifted-charts#13]
Hey there!
First of all, thanks for the hard work on this awesome library! 

I'm trying to migrate from victory chart to gifted-charts but I can't seem to get the tooltip to work on the web. I tried every example I could find and nothing works neither on hover nor on click :(

**Comment by Abhinandan-Kushwaha** [comment]
Hi @kaumac Which chart are you rendering- Bar or Line?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @kaumac This has been fixed in the latest version.

**Comment by kaumac** [comment]
Hey @Abhinandan-Kushwaha sorry for the delay.

The problem was actually the the tooltip distance from the bar is initially too big and was being cut off, I just had to decrease the distance from the bar.

Did you change the initial value to be smaller? Curious about the fix

**Comment by Abhinandan-Kushwaha** [comment]
Yes @kaumac I have made the distance smaller. Tooltip is now near the bars. 
You can adjust the distance using the `style` attribute of the component you pass in the `renderTooltip` prop.
