### ISSUE TITLE
When this package will be available on npm ?

### ISSUE THREAD

**Issue by sabativi** [Abhinandan-Kushwaha/react-gifted-charts#4]
Hello,

We are using react-native-gifted-chart on ios/android and wanted to install this for the web version.
When this will be ready ready ?

**Comment by sani-sidqam** [comment]
Waiting for the same

**Comment by gijosso** [comment]
+1

**Comment by wkappers-gmu** [comment]
+1

**Comment by Abhinandan-Kushwaha** [comment]
It is now available on npm- [react-gifted-charts](https://www.npmjs.com/package/react-gifted-charts) 🎉

cc: @sabativi @sani-sidqam @gijosso @wkappers-gmu

**Comment by bhavesh-trentium** [comment]
When I use this package in react native with typescript and run the project shows this error: `Unable to resolve "./styles.css"`.
And Socond image wise install `@types/react-gifted-charts`. Then I Install but is a package not found. How to resolve this issue?



![Screenshot 2024-08-27 144825](https://github.com/user-attachments/assets/ca830f84-a33c-4fc3-a01c-50008dd3e0bb)


![Screenshot 2024-08-27 144810](https://github.com/user-attachments/assets/2402ed62-543b-4ca5-879d-363114798b5b)


![Screenshot 2024-08-27 144938](https://github.com/user-attachments/assets/8948e8dc-c6f3-42b7-bd13-17c5e4249703)

**Comment by Abhinandan-Kushwaha** [comment]
@bhavesh-trentium This library will not work in a react-native project. It will work in ReactJS projects.

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha I have a react native expo project. And you know is supports the web also.
